// <auto-generated />
using System;
using AiWand.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AiWand.Data.Migrations
{
    [DbContext(typeof(AiWandDataContext))]
    [Migration("20190506093719_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AiWand.Core.Domain.CodeDocuments.CodeDocument", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<string>("CompanyAbb");

                    b.Property<string>("CompanyName");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator");

                    b.Property<string>("DocumentName");

                    b.Property<string>("DocumentNo");

                    b.Property<int>("DocumentStatus");

                    b.Property<int>("DownloadTimes");

                    b.Property<string>("Language");

                    b.Property<DateTime?>("ReviseTime");

                    b.Property<string>("Reviser");

                    b.Property<int>("Status");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("CodeDocument");
                });

            modelBuilder.Entity("AiWand.Core.Domain.CodeDocuments.CodePath", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<string>("CodeFile");

                    b.Property<string>("CodeFilePath");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator");

                    b.Property<string>("DocumentId");

                    b.Property<DateTime?>("ReviseTime");

                    b.Property<string>("Reviser");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("CodePath");
                });

            modelBuilder.Entity("AiWand.Core.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator");

                    b.Property<string>("Email");

                    b.Property<string>("HeadImage");

                    b.Property<string>("IP");

                    b.Property<string>("LastIP");

                    b.Property<DateTime?>("LastLoginTime");

                    b.Property<DateTime?>("LoginTime");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<string>("RealName");

                    b.Property<DateTime>("RegisterTime");

                    b.Property<string>("Remark");

                    b.Property<DateTime?>("ReviseTime");

                    b.Property<string>("Reviser");

                    b.Property<int>("Status");

                    b.Property<string>("Token");

                    b.Property<string>("UserName");

                    b.Property<int>("UserType");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
