// <auto-generated />
using System;
using AiWand.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AiWand.Data.Migrations
{
    [DbContext(typeof(AiWandDataContext))]
    partial class AiWandDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AiWand.Core.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator");

                    b.Property<string>("Email");

                    b.Property<string>("HeadImage");

                    b.Property<string>("IP");

                    b.Property<string>("LastIP");

                    b.Property<DateTime?>("LastLoginTime");

                    b.Property<DateTime?>("LoginTime");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<string>("RealName");

                    b.Property<DateTime>("RegisterTime");

                    b.Property<string>("Remark");

                    b.Property<DateTime?>("ReviseTime");

                    b.Property<string>("Reviser");

                    b.Property<int>("Status");

                    b.Property<string>("UserName");

                    b.Property<int>("UserType");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
